### PR TITLE
remove own libsass JNA binding, replace with jsass implementation

### PR DESCRIPTION
**Pull request by Danny02**
I had encoding Problems with libsass and I saw that they where fixed in a newer version.

There is a Java binding for libsass which seems to be always up to date called [JSass](https://github.com/bit3/jsass).

This pull request removes the own JNA binding and replaces it with a dependency to JSass.

### CODE REVIEW

**Comment by Danny02** [comment]
I can't see the travis site at work (proxy), but I think it could be caused by a wrong Java version.
I think JSass only works with Java 8, which would be an importened point to consider.

**Comment by Danny02** [comment]
I'm closing because this pr is mixing to much together. Will submit a new pr shortly.

**Comment by warmuuh** [comment]
Thank you... I would really like to merge this. Did not know about jsass.

**Comment by Danny02** [comment]
Hi,

I closed the pr because the only real problem was the missing utf-8
encoding in the fileoutputstream. I would have liked to provide a cleaner
pr(i.e. tests), but I'm gone for a whole month now:).

We are using a local fork atm in our project,but of course would like to
just use a release from central.

About using Jsass, I think it would be a great think for decoupling the
maven plugin from the java binding. Less to do for you. Sadly it is java 8
only but i guess we could do a pr for that on jsass too.

I can do the pull requests when I'm back, or you can start yourself if you
want of course.

Peter <notifications@github.com> schrieb am Di., 15. Dez. 2015 17:21:

**Pull request closed without merging**
